name: Publish app to DockerHub

on:
  push:
    branches:
      - master

jobs:
  publish-to-dockerhub:
    name: Publish image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, push
        uses: docker/build-push-action@v2
        with:
          context: ./express-app
          push: true
          tags: maisoup/testing:latest
